update TORNEIO
set FORMATO_EQUIPE = case FORMATO_EQUIPE
    when 'TRES_JOGADORES' then 'TRES_POR_TRES'
    when 'CINCO_JOGADORES' then 'CINCO_POR_CINCO'
    when 'SETE_JOGADORES' then 'SETE_POR_SETE'
    when 'ONZE_JOGADORES' then 'ONZE_POR_ONZE'
    else FORMATO_EQUIPE
end
where FORMATO_EQUIPE in (
    'TRES_JOGADORES',
    'CINCO_JOGADORES',
    'SETE_JOGADORES',
    'ONZE_JOGADORES'
);
