spring.datasource.url=jdbc:postgresql://localhost:5432/torneios
spring.datasource.username=torneios
spring.datasource.password=torneios

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
